In [1]:
#Import modules
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import requests
import json
import os

In [3]:
#Read by count
us_by_count = pd.read_csv("US_CRE_by_count.csv")
us_by_count.head(2)

,state,county,tract,rfgrp,prednum,prednum_moe,predrt,predrt_moe,stname,STABREV,ctname,popuni
0,1,1,0,0RF,17545,4022.9,31.66,7.26,Alabama,AL,"Autauga County, AL",55420
1,1,1,0,1-2RF,24796,4320.5,44.74,7.80,Alabama,AL,"Autauga County, AL",55420

In [5]:
#Filter Kansas and New Jersey
ks_nj_by_count = pd.DataFrame(us_by_count.loc[(us_by_count["stname"] == "Kansas") | (us_by_count["stname"] == "New Jersey"), :])

,state,county,tract,rfgrp,prednum,prednum_moe,predrt,predrt_moe,stname,STABREV,ctname,popuni
81918,20,1,0,0RF,3454,830.4,28.28,6.80,Kansas,KS,"Allen County, KS",12213
81919,20,1,0,1-2RF,5645,873.7,46.22,7.15,Kansas,KS,"Allen County, KS",12213
81920,20,1,0,3PLRF,3114,735.0,25.50,6.02,Kansas,KS,"Allen County, KS",12213
81921,20,1,952600,0RF,532,151.0,28.62,8.12,Kansas,KS,"Allen County, KS",1859
81922,20,1,952600,1-2RF,780,160.0,41.96,8.61,Kansas,KS,"Allen County, KS",1859

In [7]:
#Write to csv file
ks_nj_by_count.to_csv('ks_nj_CRE_by_count.csv')

In [8]:
#Read by percent
us_by_pct = pd.read_csv("US_CRE_by_percent.csv")
us_by_pct.head(2)

,state,county,tract,rfgrp,prednum,prednum_moe,predrt,predrt_moe,stname,STABREV,ctname,popuni
0,1,1,0,0RF,17545,4022.9,31.66,7.26,Alabama,AL,"Autauga County, AL",55420
1,1,1,0,1-2RF,24796,4320.5,44.74,7.80,Alabama,AL,"Autauga County, AL",55420

In [9]:
#Filter Kansas and New Jersey
ks_nj_by_pct = pd.DataFrame(us_by_pct.loc[(us_by_count["stname"] == "Kansas") | (us_by_pct["stname"] == "New Jersey"), :])
ks_nj_by_pct.head(5)

,state,county,tract,rfgrp,prednum,prednum_moe,predrt,predrt_moe,stname,STABREV,ctname,popuni
81918,20,1,0,0RF,3454,830.4,28.28,6.80,Kansas,KS,"Allen County, KS",12213
81919,20,1,0,1-2RF,5645,873.7,46.22,7.15,Kansas,KS,"Allen County, KS",12213
81920,20,1,0,3PLRF,3114,735.0,25.50,6.02,Kansas,KS,"Allen County, KS",12213
81921,20,1,952600,0RF,532,151.0,28.62,8.12,Kansas,KS,"Allen County, KS",1859
81922,20,1,952600,1-2RF,780,160.0,41.96,8.61,Kansas,KS,"Allen County, KS",1859

In [10]:
#Write to csv file
ks_nj_by_pct.to_csv('ks_nj_CRE_by_pct.csv')