In [28]:
#Dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
import csv
import os

In [29]:
#Store filepath in a variable:
file_one = "ManagementUnemployed_UnemploymentRate.csv"
file_two = "Construction and extraction occupations_UnemploymentRate.csv"
file_three = "Farming, fishing, and forestry occupations_UnemploymentRate.csv"
file_four = "Installation, maintenance, and repair occupations_UnemploymentRate.csv"
file_five = "Management, Business, and Financial Operations Occupations_UnemploymentRate.csv"
file_six = "Office and administrative support occupations_UnemploymentRate.csv"
file_seven = "Production occupations_UnemploymentRate.csv"
file_eight = "Professional and related occupations_UnemploymentRate.csv"
file_nine = "Sales and related occupations_UnemploymentRate.csv"
file_ten = "Transportation and material moving occupations_UnemploymentRate.csv"

In [30]:
#read the files
mgmt_unemployed_rate = pd.read_csv(file_one)
cons_unemployed_rate = pd.read_csv(file_two)
farm_unemployed_rate = pd.read_csv(file_three)
inst_unemployed_rate = pd.read_csv(file_four)
fina_unemployed_rate = pd.read_csv(file_five)
offi_unemployed_rate = pd.read_csv(file_six)
prod_unemployed_rate = pd.read_csv(file_seven)
prof_unemployed_rate = pd.read_csv(file_eight)
sale_unemployed_rate = pd.read_csv(file_nine)
tran_unemployed_rate = pd.read_csv(file_ten)

In [31]:
#removing extra rows and columns

mgmt_unemployed_rate_final = mgmt_unemployed_rate.drop(mgmt_unemployed_rate.index[[0,1,2,3,4,5,6,7,8,9,10,11]])

#insert column with static value in data frame

mgmt_unemployed_rate_final.insert(1, "Occupation", "Managment")
mgmt_unemployed_rate_final

,Labor Force Statistics from the Current Population Survey,Occupation,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
12,Year,Managment,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
13,2010,Managment,5.0,4.8,4.7,4.5,4.5,4.9,5.0,5.1,4.4,4.5,4.7,4.6
14,2011,Managment,4.7,4.4,4.3,4.0,4.4,4.7,5.0,4.9,4.4,4.4,4.2,4.2
15,2012,Managment,4.3,4.2,4.2,3.7,4.0,4.4,4.8,4.5,3.9,3.8,3.6,3.9
16,2013,Managment,3.9,3.8,3.6,3.5,3.5,4.2,4.1,3.8,3.5,3.4,3.1,2.9
17,2014,Managment,3.1,3.2,3.3,2.9,3.1,3.5,3.5,3.4,2.8,2.7,2.8,2.7
18,2015,Managment,2.9,2.7,2.4,2.4,2.4,2.9,3.1,2.9,2.4,2.2,2.1,2.0
19,2016,Managment,2.3,2.4,2.4,2.1,2.1,2.8,3.0,3.1,2.7,2.5,2.3,2.2
20,2017,Managment,2.3,2.1,2.0,2.0,1.9,2.3,2.7,2.8,2.3,2.1,2.0,2.0
21,2018,Managment,2.2,2.0,2.0,1.8,1.7,2.5,2.4,2.5,2.0,1.9,2.1,2.1
22,2019,Managment,2.5,2.0,2.0,1.6,1.7,2.4,2.4,2.3,1.9,1.8,1.8,1.8
23,2020,Managment,2.2,1.8,2.5,7.7,6.6,6.5,6.6,NaN,NaN,NaN,NaN,NaN

In [32]:
# #removing extra rows and columns
cons_unemployed_rate_final = cons_unemployed_rate.drop(cons_unemployed_rate.index[[0,1,2,3,4,5,6,7,8,9,10,11,12]])

# inserting column with static value in data frame 
cons_unemployed_rate_final.insert(1, "Occupation", "Construction")
cons_unemployed_rate_final

,Labor Force Statistics from the Current Population Survey,Occupation,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
13,2010,Construction,24.6,26.5,24.6,21.4,19.1,18.2,15.9,16.3,17.6,17.2,19.0,20.7
14,2011,Construction,22.9,22.0,20.3,17.1,16.3,15.4,13.7,13.2,13.4,14.2,13.4,16.4
15,2012,Construction,18.4,17.9,17.0,14.4,14.2,13.0,12.9,11.9,13.2,12.6,12.9,14.4
16,2013,Construction,16.8,15.8,15.8,14.3,11.7,11.1,10.8,10.5,10.1,10.5,10.3,12.1
17,2014,Construction,13.0,13.1,11.8,9.8,9.4,9.2,8.0,8.7,7.6,7.7,8.2,9.3
18,2015,Construction,11.1,11.6,11.0,8.5,7.5,7.4,6.3,7.0,7.0,7.1,6.8,9.6
19,2016,Construction,10.4,9.9,9.6,6.9,6.1,5.3,5.3,5.9,5.7,7.0,6.5,8.5
20,2017,Construction,10.3,9.7,9.9,7.6,6.4,5.3,6.3,5.9,5.5,5.7,5.6,6.8
21,2018,Construction,8.4,8.9,8.2,7.6,5.4,5.4,4.2,4.0,4.8,4.5,4.4,6.0
22,2019,Construction,7.5,6.7,5.7,5.2,3.7,4.2,4.5,4.5,3.6,4.6,5.0,6.3
23,2020,Construction,6.9,6.9,8.3,18.9,15.2,11.5,10.2,NaN,NaN,NaN,NaN,NaN

In [33]:

# #removing extra rows and columns
farm_unemployed_rate_final = farm_unemployed_rate.drop(farm_unemployed_rate.index[[0,1,2,3,4,5,6,7,8,9,10,11,12]])
# Add occupation column
# inserting column with static value in data frame 
farm_unemployed_rate_final.insert(1, "Occupation", "Farming") 
farm_unemployed_rate_final

,Labor Force Statistics from the Current Population Survey,Occupation,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
13,2010,Farming,25.9,22.7,21.8,16.7,13.3,14.2,10.9,9.6,11.9,12.5,16.9,22.5
14,2011,Farming,20.7,21.9,20.4,19.3,10.2,11.3,11.9,10.9,11.2,14.5,15.8,18.2
15,2012,Farming,22.3,19.9,19.8,17.6,10.7,10.3,10.2,10.9,9.5,10.9,15.5,18.3
16,2013,Farming,18.5,16.1,15.3,10.8,5.9,7.9,6.3,10.0,10.3,12.8,11.9,13.4
17,2014,Farming,14.2,11.3,18.7,14.0,9.8,6.4,7.4,8.6,10.5,10.2,13.4,16.9
18,2015,Farming,17.7,15.0,15.7,10.9,9.3,6.7,6.2,5.1,5.7,11.0,13.8,14.7
19,2016,Farming,15.5,13.0,12.8,9.9,8.4,10.8,7.5,5.1,9.1,7.0,12.3,15.5
20,2017,Farming,15.1,8.9,9.9,8.9,6.1,7.0,7.6,5.7,8.3,5.2,7.4,15.0
21,2018,Farming,13.2,12.5,12.1,11.6,8.0,9.0,7.0,7.3,4.2,5.0,9.8,11.1
22,2019,Farming,18.6,14.3,15.5,10.5,6.6,7.5,4.8,4.3,5.2,4.7,11.1,10.0
23,2020,Farming,16.3,13.8,10.6,12.4,8.3,7.4,7.3,NaN,NaN,NaN,NaN,NaN

In [34]:


# #removing extra rows and columns
inst_unemployed_rate_final = inst_unemployed_rate.drop(inst_unemployed_rate.index[[0,1,2,3,4,5,6,7,8,9,10,11,12]])
# Add occupation column
# inserting column with static value in data frame 
inst_unemployed_rate_final.insert(1, "Occupation", "Installation") 
inst_unemployed_rate_final

,Labor Force Statistics from the Current Population Survey,Occupation,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
13,2010,Installation,10.3,10.4,9.4,10.0,9.7,9.9,9.3,9.5,9.3,8.3,8.6,6.7
14,2011,Installation,8.3,7.1,9.2,8.6,7.8,8.1,7.9,8.4,7.5,7.2,6.1,5.8
15,2012,Installation,6.8,6.3,6.7,5.5,6.3,5.3,6.5,6.6,6.5,6.2,5.5,6.4
16,2013,Installation,6.8,6.0,4.8,4.6,6.0,5.6,5.2,5.6,4.8,5.4,5.2,5.0
17,2014,Installation,5.1,5.0,5.0,4.0,3.8,4.3,5.0,4.8,3.4,3.8,3.8,4.5
18,2015,Installation,6.2,6.1,4.9,5.0,4.6,4.2,3.8,3.2,3.5,3.0,3.5,3.5
19,2016,Installation,4.3,4.9,5.4,4.7,4.0,4.4,4.1,3.7,3.3,3.9,3.1,3.3
20,2017,Installation,3.5,4.2,3.6,2.9,4.1,3.8,2.7,3.5,3.4,3.2,3.6,3.2
21,2018,Installation,3.1,2.9,3.0,2.7,2.4,3.0,2.2,2.5,1.8,1.7,2.9,3.4
22,2019,Installation,2.8,3.2,2.5,2.7,3.0,3.0,3.4,2.9,2.2,1.5,1.6,2.0
23,2020,Installation,2.8,2.4,2.7,12.8,11.0,9.6,7.9,NaN,NaN,NaN,NaN,NaN

In [35]:

# #removing extra rows and columns
fina_unemployed_rate_final = fina_unemployed_rate.drop(fina_unemployed_rate.index[[0,1,2,3,4,5,6,7,8,9,10,11,12]])
# Add occupation column
# inserting column with static value in data frame 
fina_unemployed_rate_final.insert(1, "Occupation", "Finance") 
fina_unemployed_rate_final

,Labor Force Statistics from the Current Population Survey,Occupation,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
13,2010,Finance,5.2,5.1,5.4,5.1,4.9,4.8,4.7,4.9,4.3,5.0,5.5,5.7
14,2011,Finance,5.3,4.9,4.8,4.6,4.9,4.6,4.6,4.6,4.6,4.7,4.6,4.4
15,2012,Finance,4.5,4.4,4.4,4.0,4.1,3.8,3.8,3.7,3.5,3.6,3.8,4.1
16,2013,Finance,4.0,3.9,3.5,3.5,3.8,3.5,3.1,3.4,3.3,3.7,3.2,3.1
17,2014,Finance,3.4,3.6,3.5,3.2,3.3,2.8,2.7,2.6,2.4,2.7,2.7,2.5
18,2015,Finance,3.0,2.8,2.6,2.6,2.9,2.4,2.3,2.2,2.4,2.2,2.1,1.9
19,2016,Finance,2.3,2.6,2.5,2.4,2.4,2.5,2.4,2.5,2.8,2.5,2.3,2.4
20,2017,Finance,2.5,2.4,2.4,2.2,1.8,1.9,1.9,2.4,2.5,1.9,1.9,2.0
21,2018,Finance,2.0,2.0,2.0,1.8,1.7,2.1,1.9,2.0,2.1,2.0,2.1,2.2
22,2019,Finance,2.5,2.1,2.0,1.4,1.5,1.9,1.8,1.9,1.6,1.7,1.6,1.9
23,2020,Finance,2.3,1.8,2.2,6.2,5.1,4.8,5.1,NaN,NaN,NaN,NaN,NaN

In [36]:


# #removing extra rows and columns
offi_unemployed_rate_final = offi_unemployed_rate.drop(offi_unemployed_rate.index[[0,1,2,3,4,5,6,7,8,9,10,11,12]])
# Add occupation column
# inserting column with static value in data frame 
offi_unemployed_rate_final.insert(1, "Occupation", "Administration") 
offi_unemployed_rate_final

,Labor Force Statistics from the Current Population Survey,Occupation,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
13,2010,Administration,9.0,8.9,8.5,8.2,8.1,8.6,8.9,9.2,9.1,8.9,8.8,8.3
14,2011,Administration,8.9,8.5,8.4,7.9,8.3,8.8,8.7,9.0,8.7,8.6,8.5,8.0
15,2012,Administration,8.2,8.0,8.0,7.6,7.8,7.9,7.7,7.7,7.2,7.3,7.1,7.0
16,2013,Administration,8.4,7.6,7.4,6.9,6.8,7.0,6.9,7.1,7.1,7.0,6.7,6.4
17,2014,Administration,6.8,6.3,6.2,5.7,5.8,5.6,5.9,6.0,6.1,5.2,5.3,4.8
18,2015,Administration,5.3,5.0,5.4,4.9,4.9,4.4,4.8,4.6,4.7,4.4,4.2,3.8
19,2016,Administration,5.5,5.5,5.3,4.8,3.8,4.0,4.6,4.0,4.1,4.0,3.9,3.8
20,2017,Administration,4.8,4.9,4.4,3.5,3.6,3.8,4.0,3.9,4.3,3.8,3.7,3.5
21,2018,Administration,4.0,4.4,3.8,3.2,3.3,3.2,4.1,4.1,3.2,3.4,3.3,3.5
22,2019,Administration,4.2,3.5,3.5,3.4,4.0,4.1,4.1,3.9,3.1,3.1,3.1,2.9
23,2020,Administration,3.5,3.3,3.6,12.7,11.8,10.5,9.8,NaN,NaN,NaN,NaN,NaN

In [37]:

# #removing extra rows and columns
prod_unemployed_rate_final = prod_unemployed_rate.drop(prod_unemployed_rate.index[[0,1,2,3,4,5,6,7,8,9,10,11,12]])
# Add occupation column
# inserting column with static value in data frame 
prod_unemployed_rate_final.insert(1, "Occupation", "Production") 
prod_unemployed_rate_final

,Labor Force Statistics from the Current Population Survey,Occupation,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
13,2010,Production,15.4,15.4,16.1,13.8,13.1,12.1,12.3,11.6,12.1,12.1,12.2,11.7
14,2011,Production,12.3,12.3,11.7,11.7,11.9,12.0,11.5,10.8,10.4,9.6,9.5,10.7
15,2012,Production,10.4,10.5,9.7,9.4,8.8,9.4,9.6,9.5,8.4,8.7,7.9,9.2
16,2013,Production,10.4,9.1,8.2,8.3,9.6,8.7,9.3,8.4,9.4,7.7,7.9,7.7
17,2014,Production,7.8,7.8,7.9,7.6,7.1,6.2,7.7,6.8,6.1,6.0,6.4,6.2
18,2015,Production,7.0,7.0,6.4,5.5,6.1,5.1,6.2,5.3,4.5,4.8,5.0,5.3
19,2016,Production,6.1,6.1,5.9,5.8,6.1,4.9,5.9,5.5,6.4,5.5,5.2,5.5
20,2017,Production,6.4,6.0,5.3,4.8,4.6,5.1,5.1,5.7,4.7,3.5,3.3,4.2
21,2018,Production,4.5,4.3,4.3,4.4,4.4,3.7,4.1,3.6,3.9,4.4,3.4,3.3
22,2019,Production,4.2,3.7,4.2,3.8,3.1,3.4,4.1,3.9,4.3,4.4,3.7,4.3
23,2020,Production,4.9,5.1,5.3,18.6,15.2,11.0,11.3,NaN,NaN,NaN,NaN,NaN

In [38]:

# #removing extra rows and columns
prof_unemployed_rate_final = prof_unemployed_rate.drop(prof_unemployed_rate.index[[0,1,2,3,4,5,6,7,8,9,10,11,12]])
# Add occupation column
# inserting column with static value in data frame 
prof_unemployed_rate_final.insert(1, "Occupation", "Professional") 
prof_unemployed_rate_final

,Labor Force Statistics from the Current Population Survey,Occupation,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
13,2010,Professional,4.9,4.6,4.3,4.1,4.3,5.0,5.2,5.3,4.4,4.1,4.1,3.8
14,2011,Professional,4.3,4.1,3.9,3.5,4.0,4.9,5.3,5.1,4.4,4.1,4.0,4.0
15,2012,Professional,4.2,4.1,4.0,3.5,4.0,4.8,5.5,5.2,4.3,3.9,3.5,3.8
16,2013,Professional,3.8,3.8,3.6,3.4,3.3,4.6,4.7,4.0,3.6,3.1,2.9,2.7
17,2014,Professional,2.9,3.0,3.1,2.6,2.9,4.0,4.1,3.9,3.1,2.7,2.9,2.8
18,2015,Professional,2.9,2.7,2.2,2.3,2.1,3.2,3.6,3.3,2.4,2.2,2.2,2.1
19,2016,Professional,2.4,2.2,2.3,1.8,2.0,3.1,3.4,3.5,2.6,2.4,2.2,2.1
20,2017,Professional,2.2,1.9,1.8,1.8,2.0,2.6,3.3,3.1,2.3,2.2,2.0,2.1
21,2018,Professional,2.3,2.0,2.1,1.8,1.7,2.8,2.8,2.9,2.0,1.9,2.1,2.1
22,2019,Professional,2.4,2.0,1.9,1.8,1.8,2.7,2.9,2.6,2.1,1.8,1.9,1.7
23,2020,Professional,2.1,1.8,2.6,8.8,7.7,7.7,7.6,NaN,NaN,NaN,NaN,NaN

In [40]:

# #removing extra rows and columns
sale_unemployed_rate_final = sale_unemployed_rate.drop(sale_unemployed_rate.index[[0,1,2,3,4,5,6,7,8,9,10,11,12]])
# Add occupation column
# inserting column with static value in data frame 
sale_unemployed_rate_final.insert(1, "Occupation", "Sales") 
sale_unemployed_rate_final

,Labor Force Statistics from the Current Population Survey,Occupation,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
13,2010,Sales,10.1,10.2,9.7,9.2,9.6,9.4,10.1,9.0,9.4,9.1,8.8,8.3
14,2011,Sales,9.3,9.0,8.8,8.5,9.4,9.7,9.4,8.6,9.4,8.2,7.8,7.7
15,2012,Sales,8.2,7.9,8.1,7.6,7.9,8.4,8.3,8.6,7.9,7.0,7.3,7.0
16,2013,Sales,8.5,8.2,7.7,6.9,7.1,6.7,6.9,7.2,7.5,7.3,7.0,6.3
17,2014,Sales,7.5,7.7,6.8,5.8,6.8,6.1,6.2,5.6,5.4,5.2,5.3,5.0
18,2015,Sales,5.8,5.2,5.8,5.5,5.8,5.6,5.8,5.4,5.6,5.3,5.1,4.8
19,2016,Sales,5.0,4.4,4.4,5.2,5.1,4.9,4.9,4.8,5.2,4.4,4.6,4.6
20,2017,Sales,5.2,4.3,3.9,4.2,4.5,4.8,4.2,4.2,3.7,4.0,4.1,3.8
21,2018,Sales,4.6,4.5,4.5,4.1,4.2,4.4,4.0,3.5,4.0,3.6,3.7,3.6
22,2019,Sales,4.5,5.0,4.6,3.9,3.6,3.4,3.2,3.8,3.6,3.4,3.3,3.3
23,2020,Sales,4.5,4.2,4.3,17.1,16.2,13.3,10.9,NaN,NaN,NaN,NaN,NaN

In [42]:

# #removing extra rows and columns
tran_unemployed_rate_final = tran_unemployed_rate.drop(tran_unemployed_rate.index[[0,1,2,3,4,5,6,7,8,9,10,11,12]])
# Add occupation column
# inserting column with static value in data frame 
tran_unemployed_rate_final.insert(1, "Occupation", "Transportation") 
tran_unemployed_rate_final

,Labor Force Statistics from the Current Population Survey,Occupation,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
13,2010,Transportation,15.0,15.0,15.6,13.2,12.7,11.8,11.9,10.3,10.2,10.0,11.3,12.0
14,2011,Transportation,13.6,13.6,12.8,12.0,10.7,10.8,11.0,11.6,10.9,10.2,10.1,10.1
15,2012,Transportation,11.3,12.0,11.2,10.0,10.1,10.3,10.1,10.8,9.3,9.3,9.4,9.8
16,2013,Transportation,11.7,10.9,10.5,9.0,9.0,8.6,9.0,8.5,8.0,9.5,9.0,8.4
17,2014,Transportation,10.0,10.2,9.2,8.0,7.2,7.5,7.7,7.6,6.8,6.4,6.0,6.1
18,2015,Transportation,7.5,7.7,8.1,6.1,7.0,6.9,6.9,6.3,5.8,6.7,6.8,6.2
19,2016,Transportation,7.6,6.6,6.2,6.8,6.0,6.7,7.5,7.1,5.9,5.8,5.7,6.1
20,2017,Transportation,7.0,7.3,6.2,5.7,5.5,5.7,6.2,5.3,4.5,5.2,5.8,5.1
21,2018,Transportation,6.8,6.1,5.2,4.4,4.9,5.0,4.5,5.2,4.6,4.8,4.0,4.4
22,2019,Transportation,5.0,5.1,4.9,4.0,4.9,4.9,5.0,5.7,4.4,3.9,4.4,4.2
23,2020,Transportation,4.6,5.5,7.1,17.9,18.3,14.7,15.3,NaN,NaN,NaN,NaN,NaN